version: '3.8'

services:
  arangodb:
    image: arangodb:latest
    container_name: pdfkg-arangodb
    environment:
      - ARANGO_ROOT_PASSWORD=
    ports:
      - "8529:8529"
    volumes:
      - arangodb_data:/var/lib/arangodb3
      - arangodb_apps:/var/lib/arangodb3-apps
    restart: unless-stopped
    command:
      - arangod
      - --server.endpoint=tcp://0.0.0.0:8529

volumes:
  arangodb_data:
  arangodb_apps:
