version: '3.8'

services:
  arangodb:
    image: arangodb:latest
    container_name: pdfkg-arangodb
    environment:
      - ARANGO_ROOT_PASSWORD=
    ports:
      - "8529:8529"
    volumes:
      - arangodb_data:/var/lib/arangodb3
      - arangodb_apps:/var/lib/arangodb3-apps
    restart: unless-stopped
    command:
      - arangod
      - --server.endpoint=tcp://0.0.0.0:8529

  milvus:
    image: milvusdb/milvus:v2.3.3
    container_name: pdfkg-milvus
    security_opt:
      - seccomp:unconfined
    ports:
      - "19530:19530"
      - "9091:9091"
    volumes:
      - milvus_data:/var/lib/milvus
    restart: unless-stopped
    environment:
      - ETCD_USE_EMBED=true
      - COMMON_STORAGETYPE=local
    command: milvus run standalone

volumes:
  arangodb_data:
  arangodb_apps:
  milvus_data:
